### ISSUE TITLE
Setup isn't working (Windows 7)

### ISSUE THREAD

**Issue by simzha19** [nielsenramon/chalk#169]
So I installed Ruby, Ruby Gem, the Ruby Devkit, Jekyll, and Node. Using the Git Bash, I went into the corresponding folder and ran npm run setup and this returned:

```
> chalk@ setup C:\Users\yy229\Documents\html files\chalk-master
> bin/setup

'bin' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chalk@ setup: `bin/setup`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chalk@ setup script.
npm ERR! This is probably not a problem with npm. There is likely additional loging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to istall?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yy229\AppData\Roaming\npm-cache\_logs\2018-07-11T04_18_15629Z-debug.log


```

The log file is here:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'setup' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle chalk@~presetup: chalk@
6 info lifecycle chalk@~setup: chalk@
7 verbose lifecycle chalk@~setup: unsafe-perm in lifecycle true
8 verbose lifecycle chalk@~setup: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\yy229\Documents\html files\Chalk\node_modules\.bin;C:\Users\yy229\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Program Files\Dell\DW WLAN Card;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Windows Live\Shared;C:\apache-maven-3.3.9\bin;C:\Java\jdk1.7.0_79\bin;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\TortoiseSVN\bin;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Git\usr\bin;C:\Program Files\Git;C:\Program Files\nodejs;C:\Ruby24-x64\bin;C:\Users\yy229\AppData\Local\Programs\Python\Python36-32\Scripts;C:\Users\yy229\AppData\Local\Programs\Python\Python36-32;C:\Users\yy229\AppData\Local\Programs\Python\Launcher;C:\Program Files\Bandizip\7z;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\yy229\AppData\Local\atom\bin;C:\Users\yy229\AppData\Roaming\npm;.;.;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl;.;
9 verbose lifecycle chalk@~setup: CWD: C:\Users\yy229\Documents\html files\Chalk
10 silly lifecycle chalk@~setup: Args: [ '/d /s /c', 'bin/setup' ]
11 silly lifecycle chalk@~setup: Returned: code: 1  signal: null
12 info lifecycle chalk@~setup: Failed to exec setup script
13 verbose stack Error: chalk@ setup: `bin/setup`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid chalk@
15 verbose cwd C:\Users\yy229\Documents\html files\Chalk
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "setup"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error chalk@ setup: `bin/setup`
22 error Exit status 1
23 error Failed at the chalk@ setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

As such, I'm having trouble getting the files setup.

**Comment by xRahul** [comment]
As I understand, the commands and `bin/setup` file works only in *nix systems. You'll have to modify them for windows.

**Comment by nastareater** [comment]
Open the `package.json` file then 
change the fourth line `"setup": "bin/setup"` to `"setup": "sh bin/setup"`
Do the same thing on the deploy command

**Comment by chrispahm** [comment]
Might want to add to @nastareater's comment that you can't run `sh bin/setup` through the standard Windows `cmd`, but rather the `Git Bash` terminal that is automatically installed together with [`git` for Windows](https://www.atlassian.com/git/tutorials/git-bash) (at least that was my experience)
