### ISSUE TITLE
Error deploying docs (imcompatible character encodings)

### ISSUE THREAD

**Issue by jakewilliami** [nielsenramon/chalk#214]
After `serve`-ing the website locally and it working, I pushed to my GitHub, and it errored:
```
The tag `asset` on line 24 in `_includes/head.html` is not a recognized Liquid tag.
```

So then I added a hard constraint on `jekyll-assets` in the `Gemfile` [as per solution here](https://github.com/envygeeks/jekyll-assets/issues/342#issuecomment-360633472), but now I am getting this error when trying to deploy:
```
  Liquid Exception: incompatible character encodings: ASCII-8BIT and UTF-8 in /_layouts/post.html
jekyll 3.8.6 | Error:  incompatible character encodings: ASCII-8BIT and UTF-8
Traceback (most recent call last):
	37: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
	36: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
	35: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/bin/jekyll:23:in `<main>'
	34: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/bin/jekyll:23:in `load'
	33: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/exe/jekyll:15:in `<top (required)>'
	32: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	31: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	30: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	29: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	28: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	27: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/commands/build.rb:18:in `block (2 levels) in
 init_with_program'
	26: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/commands/build.rb:36:in `process'
	25: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/commands/build.rb:65:in `build'
	24: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/command.rb:28:in `process_site'
	23: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/site.rb:71:in `process'
	22: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/site.rb:191:in `render'
	21: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/site.rb:462:in `render_docs'
	20: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/site.rb:462:in `each_value'
	19: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/site.rb:463:in `block in render_docs'
	18: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/site.rb:463:in `each'
	17: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
	16: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/site.rb:479:in `render_regenerated'
	15: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/renderer.rb:62:in `run'
	14: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/renderer.rb:88:in `render_document'
	13: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/renderer.rb:158:in `place_in_layouts'
	12: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/renderer.rb:195:in `render_layout'
	11: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/renderer.rb:126:in `render_liquid'
	10: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
	 9: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	 8: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
	 7: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
	 6: from /Users/jakeireland/.rvm/gems/ruby-2.7.2/gems/jekyll-3.8.6/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
	 5: from /Users/jakeireland/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
	 4: from /Users/jakeireland/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
	 3: from /Users/jakeireland/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
	 2: from /Users/jakeireland/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
	 1: from /Users/jakeireland/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:97:in `render'
/Users/jakeireland/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:97:in `join': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
```

I also had to change line 11 in `bin/deploy` from 
```bash
if [ `git branch | grep gh-pages` ]
```
to
```bash
if [[ $(git branch | grep gh-pages) ]]
```
as it was erroring.

**Comment by jakewilliami** [comment]
FYI, putting [`encoding: utf-8`](https://stackoverflow.com/a/14690811/12069968) in `_config.yml` does not fix this issue, nor does [changing the line endings](https://github.com/nielsenramon/chalk/issues/195#issuecomment-545690289).

The file even seems to be a regular file:
```bash
$ file -i _layouts/post.html
_layouts/post.html: regular file
```
